name: Continuous Integration

on:
    push:
        branches: [feature/**, hotfix/**, refactor/**]
    pull_request:
        branches: [master, release, develop]

jobs:
    # init:
    #   runs-on: self-hosted
    #   # runs-on: ubuntu-18.04

    #   steps:
    #     - name: Checkout
    #       uses: actions/checkout@v2
    #     - name: Dump github context
    #       run: echo "$GITHUB_CONTEXT"
    #       shell: bash
    #       env:
    #         GITHUB_CONTEXT: ${{ toJson(github) }}

    test:
        runs-on: self-hosted
        # runs-on: ubuntu-18.04

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install dependencies
              run: npm ci
            - name: Build (if is available)
              run: npm run build --if-present
